// Generated by scripts/sync-version.mjs. Do not edit by hand.
export const LATEST_VERSION = "3.1.1" as const;
export const VERSION_SOURCE_URL = "https://edenfromseoul.github.io/EdenTool_VersionChecker/Kisetter/Version.json" as const;
