import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const VERSION_URL =
  "https://edenfromseoul.github.io/EdenTool_VersionChecker/Kisetter/Version.json";
const KNOWN_FALLBACK_VERSION = "3.1.1";
const OUTPUT_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../lib/generated-version.ts",
);
const VERSION_PATTERN = /^\d+(?:\.\d+){1,3}(?:-[0-9A-Za-z.-]+)?$/;

function normalizeVersion(value) {
  if (typeof value !== "string") return null;
  const normalized = value.trim().replace(/^v/i, "");
  return VERSION_PATTERN.test(normalized) ? normalized : null;
}

function compareVersions(left, right) {
  const leftParts = left.split("-", 1)[0].split(".").map(Number);
  const rightParts = right.split("-", 1)[0].split(".").map(Number);
  const length = Math.max(leftParts.length, rightParts.length);
  for (let index = 0; index < length; index += 1) {
    const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (difference !== 0) return difference;
  }
  return 0;
}

async function readExistingVersion() {
  try {
    const source = await fs.readFile(OUTPUT_PATH, "utf8");
    return source.match(/LATEST_VERSION = "([^"]+)"/)?.[1] ?? null;
  } catch {
    return null;
  }
}

async function fetchLatestVersion() {
  const response = await fetch(VERSION_URL, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(8000),
  });
  if (!response.ok) {
    throw new Error("Version request failed with HTTP " + response.status);
  }
  const payload = await response.json();
  const version = normalizeVersion(payload.latestVersion);
  if (!version) {
    throw new Error("Remote latestVersion is missing or invalid.");
  }
  return version;
}

const existingVersion = normalizeVersion(await readExistingVersion());
const safeExistingVersion =
  existingVersion && compareVersions(existingVersion, KNOWN_FALLBACK_VERSION) >= 0
    ? existingVersion
    : null;
let latestVersion = safeExistingVersion ?? KNOWN_FALLBACK_VERSION;
let sourceLabel = safeExistingVersion ? "existing generated value" : "known fallback";

try {
  latestVersion = await fetchLatestVersion();
  sourceLabel = "remote JSON";
} catch (error) {
  console.warn(
    "[version] Remote sync failed; using " +
      latestVersion +
      ". " +
      (error instanceof Error ? error.message : String(error)),
  );
}

const generatedSource = [
  "// Generated by scripts/sync-version.mjs. Do not edit by hand.",
  'export const LATEST_VERSION = "' + latestVersion + '" as const;',
  'export const VERSION_SOURCE_URL = "' + VERSION_URL + '" as const;',
  "",
].join("\n");

let currentSource = "";
try {
  currentSource = await fs.readFile(OUTPUT_PATH, "utf8");
} catch {}

if (currentSource !== generatedSource) {
  await fs.writeFile(OUTPUT_PATH, generatedSource, "utf8");
}
console.log("[version] Kisetter " + latestVersion + " (" + sourceLabel + ")");